name: ivimnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - joblib=1.3.2
  - matplotlib=3.8.1
  - nibabel=5.1.0
  - numpy=1.26.0
  - python=3.9.18
  - pytorch=2.1.0
  - scipy=1.11.3
  - torchvision=0.16.0
  - tqdm=4.66.1
